// Code generated by goctl. DO NOT EDIT.
// Source: trending.proto

package trendingclient

import (
	"context"

	"github.com/Hudayberdyyev/go-zero-playground/rpc/trending/trending"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = trending.Request
	Response = trending.Response

	Trending interface {
		GetList(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultTrending struct {
		cli zrpc.Client
	}
)

func NewTrending(cli zrpc.Client) Trending {
	return &defaultTrending{
		cli: cli,
	}
}

func (m *defaultTrending) GetList(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := trending.NewTrendingClient(m.cli.Conn())
	return client.GetList(ctx, in, opts...)
}
