// Code generated by goctl. DO NOT EDIT.
// Source: trending.proto

package server

import (
	"context"

	"github.com/Hudayberdyyev/go-zero-playground/rpc/trending/internal/logic"
	"github.com/Hudayberdyyev/go-zero-playground/rpc/trending/internal/svc"
	"github.com/Hudayberdyyev/go-zero-playground/rpc/trending/trending"
)

type TrendingServer struct {
	svcCtx *svc.ServiceContext
	trending.UnimplementedTrendingServer
}

func NewTrendingServer(svcCtx *svc.ServiceContext) *TrendingServer {
	return &TrendingServer{
		svcCtx: svcCtx,
	}
}

func (s *TrendingServer) GetList(ctx context.Context, in *trending.Request) (*trending.Response, error) {
	l := logic.NewGetListLogic(ctx, s.svcCtx)
	return l.GetList(in)
}
