// Code generated by goctl. DO NOT EDIT.
package types

type SignInReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type SignInResp struct {
	Token string `json:"access_token"`
}

type IdentifyReq struct {
}

type IdentifyResp struct {
	Username string `json:"username"`
}

type TrendingReq struct {
}

type TrendingResp struct {
	Content []string `json:"content"`
}
