// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/Hudayberdyyev/go-zero-playground/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthorizationMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/identify",
					Handler: IdentifyHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/trending",
					Handler: TrendingHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.OtherMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/signIn",
					Handler: SignInHandler(serverCtx),
				},
			}...,
		),
	)
}
